package raiti.RaitisMod.Core;


import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import org.lwjgl.Sys;
import raiti.RaitisMod.Core.gui.GuiHandler;
import raiti.RaitisMod.Core.server.CommonProxy;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;

@Mod(modid = RaitisModCoreMain.MODID , version = RaitisModCoreMain.VERSION , name = RaitisModCoreMain.NAME , useMetadata = true)
public class RaitisModCoreMain {
	
	@SuppressWarnings("WeakerAccess")
	public static final String MODID = "RaitisModCoreMain";
	@SuppressWarnings("WeakerAccess")
	public static final String NAME = "Raiti's Mod Core";
	@SuppressWarnings("WeakerAccess")
	public static final String VERSION = "1.0";
	
	@SuppressWarnings("unused")
	@Mod.Metadata
	private static ModMetadata METADATA;
	
	@Mod.Instance("RaitisModCoreMain")
	public static RaitisModCoreMain INSTANCE;
	
	@SuppressWarnings("WeakerAccess")
	@SidedProxy(clientSide = "raiti.RaitisMod.Core.client.ClientProxy", serverSide = "raiti.RaitisMod.Core.server.CommonProxy")
	public static CommonProxy PROXY;
	
	@EventHandler
	public void preinit(FMLPreInitializationEvent event){
		loadMeta(METADATA);
		System.out.println("Loading Raiti'sModCore:PreInit");
		RaitisModCore.preinit(event);
		
		
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		System.out.println("Loading Raiti'sModCore:Init");
		RaitisModCore.init(event);

	}
	
	@EventHandler
	public void posinit(FMLPostInitializationEvent event){
		System.out.println("Loading Raiti'sModCore:PosInit");
		
		RaitisModCore.posInit(event);
	}
	
	private void loadMeta(ModMetadata metadata){
		metadata.modId = MODID;
		metadata.name = NAME;
		metadata.version = VERSION;
		metadata.authorList.add("Raiti-chan");
		metadata.description = "Raiti's Mod Core";
		metadata.autogenerated = false;
	}
	
}
