package raiti.RaitisMod.Core;


import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import raiti.RaitisMod.Core.Server.CommonProxy;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;

/**
 * Raiti'sMOD Forge呼び出しクラス
 * <br>Created by Raiti-chan on 2016/11/18.
 *
 * @author Raiti-chan
 * @version 1.0.0
 * @since 1.0.0
 */
@Mod(modid = RaitisModCoreMain.MOD_ID, version = RaitisModCoreMain.MOD_VERSION, name = RaitisModCoreMain.MOD_NAME, useMetadata = true)
public class RaitisModCoreMain {
	
	/**
	 * MOD ID
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String MOD_ID = "RaitisModCore";
	
	/**
	 * MOD Name
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String MOD_NAME = "Raiti's Mod Core";
	
	/**
	 * MOD Version
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String MOD_VERSION = "1.0.0";
	
	/**
	 * MOD MetaData
	 */
	@SuppressWarnings("unused")
	@Mod.Metadata
	private static ModMetadata METADATA;
	
	/**
	 * MOD Instance
	 */
	@Mod.Instance("RaitisModCore")
	public static RaitisModCoreMain INSTANCE;
	
	/**
	 * Mod Proxy
	 */
	@SuppressWarnings("WeakerAccess")
	@SidedProxy(clientSide = "raiti.RaitisMod.Core.Client.ClientProxy", serverSide = "raiti.RaitisMod.Core.Server.CommonProxy")
	public static CommonProxy PROXY;
	
	//==================================================================================================================
	
	@EventHandler
	public void preinit(FMLPreInitializationEvent event){
		loadMeta(METADATA);
		System.out.println("Loading Raiti'sModCore:PreInit");
		RaitisModCore.preinit(event);
		
		
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		System.out.println("Loading Raiti'sModCore:Init");
		RaitisModCore.init(event);

	}
	
	@EventHandler
	public void posinit(FMLPostInitializationEvent event){
		System.out.println("Loading Raiti'sModCore:PosInit");
		
		RaitisModCore.posInit(event);
	}
	
	/**
	 * メタデータ記載
	 * @param metadata メタデータインスタンス
	 */
	private void loadMeta(ModMetadata metadata){
		metadata.modId = MOD_ID;
		metadata.name = MOD_NAME;
		metadata.version = MOD_VERSION;
		metadata.authorList.add("Raiti-chan");
		metadata.description = "Raiti's Mod Core";
		metadata.autogenerated = false;
	}
	
}
